from test_suite.test_crispy import *
from test_suite.test_fields import *
from test_suite.test_files import *
from test_suite.test_misc import *
from test_suite.test_pre_processing import *
from test_suite.test_processors import *
from test_suite.test_text import *
from test_suite.test_utils import *
from test_suite.test_view import *
